name: mufc
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.2.1
  - r-tidyverse=1.3.2
  - r-rmarkdown=2.17
  - r-devtools
  - wget=1.20.3
  - snakemake=7.14.0
  - graphviz=5.0.1
  - coreutils=8.32